# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none
#- main

pool:
  vmImage: 'windows-latest'

variables:
  resource-group: "ghazdo-workshops"
  BuildConfiguration: "Release"
  BuildPlatform: "any cpu"
  Parameters.RestoreBuildProjects: "**/*.csproj"
  Parameters.TestProjects: "**/*[Tt]ests/*.csproj"
  webapp_name: eShopWeb
  advancedsecurity.submittoadvancedsecurity: true

stages:
- stage: 'AdvancedSecurityScan'
  displayName: 'Advanced Security'
  jobs:
  - job: 
    displayName: 'Advanced Security Scanning'
    steps:
    
    # Setup Node.js environment
    - task: NodeTool@0
      displayName: 'Use Node 10.16.3'
      inputs:
        versionSpec: 10.16.3
    
    # Initializes the CodeQL tools for scanning.
    - task: AdvancedSecurity-Codeql-Init@1
      inputs:
        languages: 'csharp, javascript'

    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    - task: AdvancedSecurity-Codeql-Autobuild@1
    
    # Performs CodeQL Analysis
    - task: AdvancedSecurity-Codeql-Analyze@1
      
    # Publish Results to Advance Security Dashboard
    - task: AdvancedSecurity-Publish@1